#!/bin/bash
RAILS_ENV=production
export RAILS_ENV
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH
 # bin/bundle update
 #bin/rake assets:precompile
#echo "MySQL DUMP"
 #mysqldump diaspora_production > /Users/adiom/Documents/Canfly/backup/diaspora_production_(date +"%Y-%m-%d").sql
./script/server 
